INTENT_LEDGER_FIELDS = [
    "intent_id",
    "release_id",
    "origin_release_id",
    "symbol",
    "action_type",
    "desired_state",
    "actual_state",
    "target_weight_before",
    "target_weight_after",
    "delta_weight",
    "delta_shares",
    "priority",
    "urgency",
    "reason",
    "status",
    "dispatch_block_reason",
    "continuation_status",
    "continuation_count",
    "continuation_note",
    "supersedes_intent_id",
    "replaced_by_intent_id",
    "manual_override_flag",
    "reconcile_required",
    "created_at",
    "updated_at",
    "expires_at",
    "latest_order_id",
    "latest_fill_id",
]

OPEN_INTENT_STATUSES = {"planned", "submitted", "acknowledged", "partial_fill", "cancel_requested"}
