ORDER_LEDGER_FIELDS = [
    "order_id",
    "intent_id",
    "release_id",
    "symbol",
    "broker_order_id",
    "cl_ord_id",
    "submit_time",
    "side",
    "price_type",
    "qty",
    "filled_qty",
    "remaining_qty",
    "submit_price",
    "status",
    "status_reason",
    "cancel_requested",
    "cancel_requested_at",
    "cancel_reason",
    "cancel_result",
    "updated_at",
]

OPEN_ORDER_STATUSES = {
    "planned",
    "submitted",
    "acknowledged",
    "partial_fill",
    "cancel_requested",
    "New",
    "PartiallyFilled",
    "PendingNew",
    "PendingCancel",
}
