from __future__ import annotations

from datetime import datetime
from typing import Any, Dict


MARKET_STATE_FIELDS = [
    "date",
    "generated_at",
    "trend_score",
    "breadth_score",
    "liquidity_score",
    "style_score",
    "market_regime_score",
    "market_regime",
    "style_bias",
    "mechanism_bias",
    "risk_budget_multiplier",
    "turnover_multiplier",
    "entry_strictness",
    "new_position_policy",
    "de_risk_hint",
    "hs300_ret_1",
    "hs300_ret_5",
    "hs300_ret_20",
    "hs300_above_ma20",
    "hs300_above_ma60",
    "avg_pct_chg",
    "median_pct_chg",
    "advancers_ratio",
    "large_drop_ratio",
    "strong_up_ratio",
    "limit_down_ratio",
    "total_amount",
    "total_amount_ratio_20",
    "median_turnover_rate",
    "median_turnover_ratio_20",
    "large_cap_return_1d",
    "small_cap_return_1d",
    "size_spread_1d",
    "mechanism_lead_score",
]


def default_market_state_payload(now_text: str = "", trade_date: str = "") -> Dict[str, Any]:
    generated_at = str(now_text or datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
    date = str(trade_date or generated_at[:10])
    return {
        "date": date,
        "generated_at": generated_at,
        "trend_score": 0.0,
        "breadth_score": 0.0,
        "liquidity_score": 0.0,
        "style_score": 0.0,
        "market_regime_score": 0.0,
        "market_regime": "neutral",
        "style_bias": "balanced",
        "mechanism_bias": "balanced",
        "risk_budget_multiplier": 1.0,
        "turnover_multiplier": 1.0,
        "entry_strictness": 0.5,
        "new_position_policy": "allow",
        "de_risk_hint": "market_state_unavailable",
        "hs300_ret_1": 0.0,
        "hs300_ret_5": 0.0,
        "hs300_ret_20": 0.0,
        "hs300_above_ma20": False,
        "hs300_above_ma60": False,
        "avg_pct_chg": 0.0,
        "median_pct_chg": 0.0,
        "advancers_ratio": 0.0,
        "large_drop_ratio": 0.0,
        "strong_up_ratio": 0.0,
        "limit_down_ratio": 0.0,
        "total_amount": 0.0,
        "total_amount_ratio_20": 1.0,
        "median_turnover_rate": 0.0,
        "median_turnover_ratio_20": 1.0,
        "large_cap_return_1d": 0.0,
        "small_cap_return_1d": 0.0,
        "size_spread_1d": 0.0,
        "mechanism_lead_score": 0.0,
        "mechanism_multipliers": {
            "trend_capex": 1.0,
            "price_inventory": 1.0,
            "macro_style": 1.0,
            "balanced": 1.0,
        },
    }
