# -*- coding: utf-8 -*-
"""GitHub 上传用的本地配置模板。

复制为 `local_settings.py` 后，再按本机环境填写真实路径和密钥。
"""
from __future__ import annotations

import os
from pathlib import Path


RUN_MODE = "integrated_supervisor"  # integrated_supervisor / research_only / release_only / execution_only / full_cycle / industry_router_only / evidence_audit_only
DEFAULT_RUN_PROFILE = "quick_test"  # overnight / daily_production / quick_test
LOOKBACK_HOURS = 24
DOWNLOAD_HIGH_VALUE_PDF = True
MAX_PDF_FETCH_PER_RUN = 12
MAX_PRIORITY_EVENTS = 12
MAX_CNINFO_PAGES_PER_MARKET = 3
ENABLE_CNINFO = True
ENABLE_SSE = True
ENABLE_SZSE = True
ENABLE_TUSHARE_NEWS = True
ENABLE_TUSHARE_MAJOR_NEWS = True
TUSHARE_NEWS_SOURCES = ["sina", "cls", "wallstreetcn"]
TUSHARE_MAJOR_NEWS_SOURCES = ["新浪财经", "华尔街见闻", "财联社"]
TUSHARE_NEWS_MAX_SOURCES_PER_RUN = 1
TUSHARE_MAJOR_NEWS_MAX_SOURCES_PER_RUN = 3
TUSHARE_NEWS_RATE_WINDOW_SECONDS = 60
TUSHARE_NEWS_RATE_MAX_CALLS = 1
TUSHARE_MAJOR_NEWS_RATE_WINDOW_SECONDS = 3600
TUSHARE_MAJOR_NEWS_RATE_MAX_CALLS = 4
ENABLE_OPENAI_RESEARCH = True
ENABLE_DEEPSEEK_WORKER = True
ENABLE_LOCAL_OLLAMA_RESEARCH = True
ENABLE_LLM_TRACE = True
ENABLE_MARKET_PIPELINE = True
ENABLE_TUSHARE_REALTIME_QUOTE = True
TUSHARE_REALTIME_QUOTE_SOURCE = "sina"
TUSHARE_REALTIME_QUOTE_BATCH_SIZE = 200
ENABLE_TUSHARE_REALTIME_LIST = True
TUSHARE_REALTIME_LIST_SOURCE = "dc"
TUSHARE_REALTIME_LIST_LIMIT = 120
ENABLE_TUSHARE_REALTIME_TICK = True
TUSHARE_REALTIME_TICK_SOURCE = "sina"
TUSHARE_REALTIME_TICK_SYMBOL_LIMIT = 6
ENABLE_TUSHARE_RT_MIN = True
INTRADAY_RT_MIN_PROVIDER = "eastmoney"  # eastmoney / tushare
INTRADAY_RT_MIN_FALLBACK_PROVIDER = "tushare"
TUSHARE_RT_MIN_FREQ = "1MIN"
TUSHARE_RT_MIN_SYMBOL_LIMIT = 12
ENABLE_EASTMONEY_INTRADAY_KLINE = True
EASTMONEY_INTRADAY_KLINE_BASE_URL = "https://push2his.eastmoney.com/api/qt/stock/kline/get"
EASTMONEY_TIMEOUT_SECONDS = 8.0
EASTMONEY_SLEEP_SECONDS = 0.15
EASTMONEY_MAX_RETRY = 2
ENABLE_GLOBAL_OBJECTIVE = True
GLOBAL_OBJECTIVE_MIN_EVIDENCE_SCORE = 0.35
GLOBAL_OBJECTIVE_MAX_HARVEST_RISK = 0.85
GLOBAL_OBJECTIVE_MAX_FAMILY_CONCENTRATION = 0.60
GLOBAL_OBJECTIVE_MIN_EXECUTION_SCORE = 0.30
GLOBAL_OBJECTIVE_MIN_CANDIDATE_COUNT = 3
GLOBAL_OBJECTIVE_MAX_GUARDRAIL_PENALTY = 0.78
GLOBAL_OBJECTIVE_MIN_INCREMENTAL_VALUE_SCORE = 0.28
GLOBAL_OBJECTIVE_OUTCOME_WEIGHT = 0.22
GLOBAL_OBJECTIVE_EVIDENCE_WEIGHT = 0.24
GLOBAL_OBJECTIVE_DIVERSITY_WEIGHT = 0.18
GLOBAL_OBJECTIVE_EXECUTION_WEIGHT = 0.18
GLOBAL_OBJECTIVE_ADVERSARIAL_WEIGHT = 0.18
GLOBAL_OBJECTIVE_GUARDRAIL_WEIGHT = 0.12
GLOBAL_OBJECTIVE_EXPLORATION_BUDGET = 0.15
GLOBAL_OBJECTIVE_MAX_CYCLES = 3
TUSHARE_RAPID_REFRESH_REQUIRE_TRADE_SESSION = True
TUSHARE_RAPID_REFRESH_SYMBOL_LIMIT = 8
TUSHARE_RAPID_REFRESH_SKIP_LIST = True
TUSHARE_RAPID_REFRESH_SKIP_TICK = True
TUSHARE_RAPID_REFRESH_RT_MIN_ENABLED = True
ENABLE_EXECUTION_BRIDGE = False
ENABLE_DAILY_STRATEGY_FEEDBACK = True
ENABLE_INDUSTRY_ROUTER = True
ENABLE_MARKET_STATE_ENGINE = True
ENABLE_INTEGRATED_THESIS = True
ENABLE_TECHNICAL_CONFIRMATION = True

MAX_EVENTS_PER_RUN = 18
DEEPSEEK_BATCH_SIZE = 6
LLM_MIN_EVENT_SCORE = 1.35
MAX_CONTENT_CHARS_PER_EVENT = 1800
SAVE_EXTRACT_SUMMARY = True

TOKEN_PLAN_MIN_INTERVAL_HOURS = 24
SUPERVISOR_RUN_FOREVER = False
SUPERVISOR_MAX_TICKS = 1
SUPERVISOR_SLEEP_SECONDS = 300
V5_GPU_MAX_CYCLES_PER_TICK = 8
V5_GPU_DRY_RUN = False
REQUIRE_GPU = True
STRATEGY_FEEDBACK_LOOKBACK_DAYS = 5
DEFENSIVE_DAILY_RETURN_THRESHOLD = -0.02
DEFENSIVE_THREE_DAY_RETURN_THRESHOLD = -0.03
AGGRESSIVE_DAILY_RETURN_THRESHOLD = 0.015
AGGRESSIVE_THREE_DAY_RETURN_THRESHOLD = 0.02

OVERNIGHT_V5_GPU_MAX_CYCLES_PER_TICK = 8
OVERNIGHT_TOKEN_PLAN_MIN_INTERVAL_HOURS = 24
OVERNIGHT_MAX_PDF_FETCH_PER_RUN = 12
OVERNIGHT_MAX_EVENTS_PER_RUN = 18
OVERNIGHT_DEEPSEEK_BATCH_SIZE = 6
OVERNIGHT_MAX_PRIORITY_EVENTS = 12

QUICK_TEST_V5_GPU_MAX_CYCLES_PER_TICK = 1
QUICK_TEST_TOKEN_PLAN_MIN_INTERVAL_HOURS = 24
QUICK_TEST_MAX_PDF_FETCH_PER_RUN = 2
QUICK_TEST_MAX_EVENTS_PER_RUN = 6
QUICK_TEST_DEEPSEEK_BATCH_SIZE = 2
QUICK_TEST_MAX_PRIORITY_EVENTS = 4

DAILY_PRODUCTION_V5_GPU_MAX_CYCLES_PER_TICK = 3
DAILY_PRODUCTION_TOKEN_PLAN_MIN_INTERVAL_HOURS = 24
DAILY_PRODUCTION_MAX_PDF_FETCH_PER_RUN = 6
DAILY_PRODUCTION_MAX_EVENTS_PER_RUN = 12
DAILY_PRODUCTION_DEEPSEEK_BATCH_SIZE = 4
DAILY_PRODUCTION_MAX_PRIORITY_EVENTS = 8

INDUSTRY_ROUTER_HISTORY_LOOKBACK_DAYS = 14
INDUSTRY_ROUTER_ENABLE_BACKTEST = True
INDUSTRY_ROUTER_BACKTEST_HORIZONS = [1, 2]
INDUSTRY_ROUTER_BACKTEST_TOP_K = 3
INDUSTRY_ROUTER_ENABLE_CONTEXT_PACK = True
INDUSTRY_ROUTER_ENABLE_SOURCE_FETCH = True
INDUSTRY_ROUTER_SOURCE_FETCH_TIMEOUT_SECONDS = 8
INDUSTRY_ROUTER_SOURCE_FETCH_CACHE_HOURS = 12
INDUSTRY_ROUTER_SOURCE_FETCH_MAX_SOURCES_PER_RUN = 9
INDUSTRY_ROUTER_SOURCE_FETCH_LLM_DISCOVERY_ENABLED = True
INDUSTRY_ROUTER_SOURCE_FETCH_LLM_PROVIDER = "deepseek_worker"
INDUSTRY_ROUTER_SOURCE_FETCH_LLM_TIMEOUT_SECONDS = 20
INDUSTRY_ROUTER_SOURCE_FETCH_LLM_MAX_CANDIDATES = 5
MARKET_STATE_USE_ROUTER_BIAS = True
INTEGRATED_THESIS_PORTFOLIO_BUDGET_OVERLAY = True
INTEGRATED_THESIS_SOFT_GATE_ADMISSION = True
PORTFOLIO_MARKET_STATE_AWARE_SIZING = True
PORTFOLIO_TECHNICAL_CONFIRMATION_GATE = False

ENABLE_PORTFOLIO_RECOMMENDATION = True
PORTFOLIO_MAX_NAMES = 20
PORTFOLIO_SINGLE_NAME_CAP = 0.10
PORTFOLIO_TOTAL_EXPOSURE_CAP = 1.00
PORTFOLIO_SIMULATION_READY_NEED_GATE = False
PORTFOLIO_ENABLE_POST_FILTER_REWEIGHT = True
PORTFOLIO_MIN_EXPOSURE_FILL_RATIO = 0.75
PORTFOLIO_ENFORCE_EXECUTABLE_UNIVERSE = True
PORTFOLIO_EXECUTABLE_ALLOWED_SUFFIXES = [".SH", ".SZ"]
PORTFOLIO_EXECUTABLE_REQUIRE_TRADABLE_BASIC = True
PORTFOLIO_ACCOUNT_SIZE_AWARE_SIZING = True
PORTFOLIO_ACCOUNT_SIZE_SLOT_BUDGET_RATIO = 0.96
PORTFOLIO_ACCOUNT_SIZE_MIN_WEIGHT_BUFFER = 1.05
PORTFOLIO_ACCOUNT_SIZE_MAX_SINGLE_NAME_CAP = 0.35
PORTFOLIO_BROAD_CANDIDATE_POOL_LIMIT = 48
PORTFOLIO_HARD_DATA_CANDIDATE_POOL_ENABLED = True
PORTFOLIO_HARD_DATA_CANDIDATE_WEIGHTS = {"seed_weight": 0.18, "pred_score": 0.42, "valuation": 0.24, "liquidity": 0.16}
PORTFOLIO_LLM_CANDIDATE_WEAK_ACCEPT_THRESHOLD = 6
PORTFOLIO_ENABLE_INTELLIGENT_OUTER_ALLOCATOR = False
PORTFOLIO_INTELLIGENT_OUTER_ALLOCATOR_REPLACES_INTERNAL_GATES = False
PORTFOLIO_PRE_RELEASE_INTRADAY_PROXY_OBJECTIVE_ENABLED = True
PORTFOLIO_PRE_RELEASE_PROXY_MAX_SPREAD_PCT = 0.028
PORTFOLIO_PRE_RELEASE_PROXY_TURNOVER_ENFORCE = True
PORTFOLIO_PRE_RELEASE_PROXY_DIVERSIFICATION_FLATTEN = True
PORTFOLIO_PRE_RELEASE_PROXY_CASH_HEADROOM_FLOOR = 0.04
PORTFOLIO_PRE_RELEASE_PROXY_HHI_TRIGGER = 0.18
PORTFOLIO_PRE_RELEASE_PROXY_FLATTEN_GAMMA = 0.94
PORTFOLIO_PRE_RELEASE_PROXY_FAIL_OPEN = True
ENABLE_PORTFOLIO_CANDIDATE_LLM_REVIEW = False
PORTFOLIO_CANDIDATE_LLM_PROVIDER = "deepseek_worker"
PORTFOLIO_CANDIDATE_LLM_TIMEOUT_SECONDS = 45
PORTFOLIO_CANDIDATE_LLM_MAX_INPUT_ROWS = 18
PORTFOLIO_CANDIDATE_LLM_SYMBOL_BOOST = 0.10
PORTFOLIO_CANDIDATE_LLM_MECHANISM_BOOST = 0.05
PORTFOLIO_CANDIDATE_LLM_EVENT_BOOST = 0.04
PORTFOLIO_CANDIDATE_LLM_BLOCKED_PENALTY = 0.25
ENABLE_STRATEGY_ACTIVATION = True
STRATEGY_ACTIVATION_BLEND_WEIGHT = 0.32
ENABLE_STRATEGY_ACTIVATION_LLM = False
STRATEGY_ACTIVATION_LLM_PROVIDER = "deepseek_worker"
STRATEGY_ACTIVATION_LLM_TIMEOUT_SECONDS = 40
STRATEGY_ACTIVATION_LLM_MAX_INPUT_ROWS = 16
ENABLE_EVIDENCE_AUDIT = True
EVIDENCE_AUDIT_PORTFOLIO_GATE_ENABLED = True
EVIDENCE_AUDIT_RUN_AFTER_PORTFOLIO_RECOMMENDATION = True
EVIDENCE_AUDIT_REBUILD_PORTFOLIO_AFTER_AUDIT = True
EVIDENCE_AUDIT_BLOCK_EXECUTION_ON_FAILURE = True
EVIDENCE_AUDIT_LLM_PROVIDER = "deepseek_worker"
EVIDENCE_AUDIT_LLM_TIMEOUT_SECONDS = 60
EVIDENCE_AUDIT_MAX_CANDIDATES = 40
EVIDENCE_AUDIT_MAX_RESULTS_PER_QUERY = 3
EVIDENCE_AUDIT_MAX_SOURCES_PER_SYMBOL = 8
EVIDENCE_AUDIT_FETCH_TIMEOUT_SECONDS = 12
EVIDENCE_AUDIT_MAX_PAGE_CHARS = 8000
EVIDENCE_AUDIT_GRADE_WEIGHT_MULTIPLIERS = {"A": 1.10, "B": 1.04, "C": 0.92, "D": 0.55, "F": 0.0}
EVIDENCE_AUDIT_QUERY_TEMPLATES = [
    "{base} {code} 公告 业绩预告 业绩快报 利润增长",
    "{base} {code} 年报 季报 营收 净利润 现金流 毛利率",
    "{base} {code} 中标 合同 订单 客户 供货",
    "{base} {code} 减持 质押 冻结 立案 调查 处罚 诉讼",
    "{base} {code} 退市风险 ST 非标审计 业绩亏损",
    "{base} {code} 涨价 产能 扩产 停产 产品价格",
]
EVIDENCE_AUDIT_ALLOW_DOMAINS = [
    "cninfo.com.cn",
    "sse.com.cn",
    "szse.cn",
    "eastmoney.com",
    "stcn.com",
    "cs.com.cn",
    "thepaper.cn",
    "gov.cn",
    "ccgp.gov.cn",
]
ENABLE_PORTFOLIO_V2A = True
PORTFOLIO_ENABLE_LIFECYCLE_STATE_MACHINE = True
PORTFOLIO_ENABLE_ADMISSION_REPLACEMENT = True
PORTFOLIO_ENABLE_SOFT_CROWDING_PENALTY = True
PORTFOLIO_ENABLE_RICH_PORTFOLIO_AUDIT = True
PORTFOLIO_V2A_PILOT_MAX_WEIGHT = 0.04
PORTFOLIO_V2A_BUILD_SPEED = 1.25
PORTFOLIO_V2A_TRIM_SPEED = 0.72
PORTFOLIO_V2A_REPLACEMENT_IMPROVEMENT_THRESHOLD = 0.08
PORTFOLIO_V2A_SOFT_CROWDING_PENALTY_STRENGTH = 0.08
ENABLE_PORTFOLIO_CONTROL = True
PORTFOLIO_CONTROL_DRIFT_THRESHOLD = 0.005
PORTFOLIO_CONTROL_MAX_DAILY_TURNOVER_RATIO = 0.45
PORTFOLIO_CONTROL_DYNAMIC_ACCOUNT_SCALING_ENABLED = True
PORTFOLIO_CONTROL_DYNAMIC_ACCOUNT_MAX_TURNOVER_RATIO = 0.90
PORTFOLIO_CONTROL_DYNAMIC_ACCOUNT_MAX_SINGLE_BUY_NAV_RATIO_CAP = 0.45
PORTFOLIO_CONTROL_DYNAMIC_ACCOUNT_MAX_SINGLE_BUY_CASH_RATIO_CAP = 0.50
PORTFOLIO_CONTROL_ENABLE_EXECUTION_FEEDBACK = True
PORTFOLIO_CONTROL_ENABLE_DEV_LOG_SNAPSHOT = True
PORTFOLIO_CONTROL_DEV_LOG_TOP_HOLDINGS = 8
PORTFOLIO_CONTROL_ALLOW_ODD_LOT_EXIT = True
PORTFOLIO_CONTROL_BOOTSTRAP_DIVERSIFICATION_ENABLED = True
PORTFOLIO_CONTROL_BOOTSTRAP_MAX_CURRENT_EXPOSURE_RATIO = 0.05
PORTFOLIO_CONTROL_BOOTSTRAP_MIN_NAMES = 8
PORTFOLIO_CONTROL_BOOTSTRAP_SLOT_BUDGET_RATIO = 0.95
PORTFOLIO_CONTROL_SMALL_ACCOUNT_SLICING_ENABLED = True
PORTFOLIO_CONTROL_SMALL_ACCOUNT_NAV_THRESHOLD = 50000.0
PORTFOLIO_CONTROL_SMALL_ACCOUNT_MAX_SINGLE_BUY_NAV_RATIO = 0.22
PORTFOLIO_CONTROL_SMALL_ACCOUNT_MAX_SINGLE_BUY_CASH_RATIO = 0.28
PORTFOLIO_CONTROL_LLM_FAVORED_SCORE_BOOST = 75.0
ENABLE_OMS = True
OMS_USE_BROKER_TRUTH_FOR_V2A_CONTINUITY = True
OMS_INTENT_EXPIRY_DAYS = 3
OMS_CONTROL_FEEDBACK_LOOKBACK_RUNS = 20
OMS_RESEARCH_META_LOOKBACK_RUNS = 60
OMS_COMPAT_WRITE_LATEST_ACCOUNT_STATE = True
OMS_ENABLE_BROKER_CANCEL = True
EXECUTION_ACCOUNT_MODE = "precision"  # simulation / precision
PRECISION_TRADE_ENABLED = True
ALLOW_INTEGRATED_PRECISION_EXECUTION = True
EXECUTION_IGNORE_MARKET_PANIC_REDUCE_ONLY = False
EXECUTION_ALLOW_UNFINISHED_ORDERS_RECONCILE = False
ENABLE_EXECUTION_MANAGEMENT = True
EMS_MAX_CHILD_ORDER_RATIO = 0.20
EMS_STAGED_ENTRY_DELAY_SECONDS = 45
EMS_ALLOW_CANCEL_REPLACE = True
ENABLE_EXECUTION_LLM_REVIEW = True
EXECUTION_LLM_REVIEW_PROVIDER = "deepseek_worker"
EXECUTION_LLM_REVIEW_TIMEOUT_SECONDS = 45
EXECUTION_LLM_REVIEW_MAX_TARGET_ITEMS = 8
EXECUTION_LLM_REVIEW_MAX_BLOCKED_SYMBOLS = 3
EXECUTION_LLM_REVIEW_ALLOW_REDUCE_ONLY = True
EXECUTION_LLM_REVIEW_TURNOVER_MULTIPLIER_FLOOR = 0.6
EXECUTION_LLM_REVIEW_TURNOVER_MULTIPLIER_CAP = 1.15
ENABLE_TRADE_RELEASE = True
TRADE_RELEASE_VALID_AFTER_TIME = "09:30:30"
TRADE_RELEASE_EXPIRES_AT_TIME = "15:00:00"
TRADE_RELEASE_CALENDAR_LOOKBACK_DAYS = 7
TRADE_RELEASE_CALENDAR_FORWARD_DAYS = 45
PACKAGE_ROOT = Path(__file__).resolve().parents[1]
PROJECT_ROOT = PACKAGE_ROOT
REPO_ROOT = PACKAGE_ROOT.parents[1]
ENABLE_TRADE_CLOCK = True
TRADE_CLOCK_TIMEZONE = "Asia/Shanghai"
TRADE_CLOCK_POLL_SECONDS = 30
ENABLE_TRADE_CLOCK_REMOTE_DELEGATE = False
TRADE_CLOCK_REMOTE_DELEGATE_REMOTE_USER = "ubuntu"
TRADE_CLOCK_REMOTE_DELEGATE_REMOTE_HOST = "43.129.28.141"
TRADE_CLOCK_REMOTE_DELEGATE_REMOTE_REPO_ROOT = "/opt/ashare_runtime"
TRADE_CLOCK_REMOTE_DELEGATE_PYTHON = "/usr/bin/python3"
TRADE_CLOCK_REMOTE_DELEGATE_PHASES = ["research_refresh", "release_refresh", "summary"]
TRADE_CLOCK_REMOTE_DELEGATE_FALLBACK_TO_LOCAL = True
TRADE_CLOCK_REMOTE_DELEGATE_SSH_OPTIONS = ["-o", "BatchMode=yes", "-o", "ConnectTimeout=8"]
# Account NAV/cash + concentration snapshot (heartbeat + data/trade_clock/clock_account_snapshot.json)
CLOCK_ACCOUNT_SNAPSHOT_ENABLED = True
CLOCK_CONCENTRATION_TOP1_HIGH = 0.35
CLOCK_CONCENTRATION_TOP1_ELEVATED = 0.22
CLOCK_CONCENTRATION_HHI_HIGH = 0.22
CLOCK_CONCENTRATION_HHI_ELEVATED = 0.15
TRADE_CLOCK_RUNTIME_HOT_RELOAD_ENABLED = False
TRADE_CLOCK_RUNTIME_HOT_RELOAD_CHECK_INTERVAL_SECONDS = 20
TRADE_CLOCK_RUNTIME_HOT_RELOAD_SCRIPTS_ROOT = str(REPO_ROOT / "scripts")
TRADE_CLOCK_RUNTIME_HOT_RELOAD_HUB_ROOT = str(PROJECT_ROOT / "engine")
TRADE_CLOCK_RUNTIME_HOT_RELOAD_BRIDGE_ROOT = str(PROJECT_ROOT.parents[0] / "live_execution_bridge")
TRADE_CLOCK_RUNTIME_HOT_RELOAD_CSHARP_ROOT = str(REPO_ROOT / "csharp_runtime_skeleton")
TRADE_CLOCK_EXECUTION_WINDOWS = [
    {"label": "morning_primary", "start": "09:30:30", "end": "10:00:00"},
    {"label": "afternoon_primary", "start": "13:00:00", "end": "14:50:00"},
]
TRADE_CLOCK_SCHEDULER_ENABLED = True
TRADE_CLOCK_SCHEDULER_PROFILE = "daily_production"
TRADE_CLOCK_SCHEDULER_LOG_TAIL_LINES = 30
TRADE_CLOCK_RESEARCH_REFRESH_PROFILE = "daily_production"
TRADE_CLOCK_RELEASE_REFRESH_PROFILE = "daily_production"
TRADE_CLOCK_DATA_CONSISTENCY_GATE_ENABLED = True
TRADE_CLOCK_DATA_CONSISTENCY_GATE_FAIL_OPEN = False
TRADE_CLOCK_DATA_CONSISTENCY_MAX_MARKET_AGE_DAYS = 4
TRADE_CLOCK_DATA_CONSISTENCY_MAX_MARKET_TABLE_SPREAD_DAYS = 1
TRADE_CLOCK_DATA_CONSISTENCY_REQUIRE_TODAY_REFRESH_PHASES = [
    "research_refresh",
    "release_refresh",
    "preopen_gate",
    "simulation",
    "midday_review",
    "afternoon_execution",
    "summary",
]
TRADE_CLOCK_DATA_CONSISTENCY_REQUIRED_TODAY_PIPELINES = [
    "affordable_data_refresh",
    "external_research_refresh",
    "research_fact_refresh",
    "industry_hard_factor_refresh",
]
TRADE_CLOCK_PHASE_RESEARCH_TIME = "15:05:00"
TRADE_CLOCK_PHASE_RELEASE_TIME = "15:10:00"
TRADE_CLOCK_MORNING_RESEARCH_REFRESH_ENABLED = True
TRADE_CLOCK_MORNING_RELEASE_REFRESH_ENABLED = True
TRADE_CLOCK_PHASE_RESEARCH_REFRESH_TIME = "08:35:00"
TRADE_CLOCK_PHASE_RELEASE_REFRESH_TIME = "08:55:00"
TRADE_CLOCK_PHASE_PREOPEN_GATE_TIME = "09:20:00"
TRADE_CLOCK_PHASE_SIMULATION_TIME = "09:30:35"
TRADE_CLOCK_PHASE_SHADOW_TIME = "09:35:00"
TRADE_CLOCK_PHASE_MIDDAY_REVIEW_TIME = "11:35:00"
TRADE_CLOCK_PHASE_AFTERNOON_EXECUTION_TIME = "13:05:00"
TRADE_CLOCK_PHASE_AFTERNOON_SHADOW_TIME = "13:15:00"
TRADE_CLOCK_PHASE_SUMMARY_TIME = "15:20:00"
TRADE_CLOCK_RESEARCH_TIMEOUT_MINUTES = 420
TRADE_CLOCK_RELEASE_TIMEOUT_MINUTES = 30
TRADE_CLOCK_RESEARCH_REFRESH_TIMEOUT_MINUTES = 15
TRADE_CLOCK_RELEASE_REFRESH_TIMEOUT_MINUTES = 10
TRADE_CLOCK_PREOPEN_GATE_TIMEOUT_MINUTES = 15
TRADE_CLOCK_SIMULATION_TIMEOUT_MINUTES = 45
TRADE_CLOCK_SHADOW_TIMEOUT_MINUTES = 30
TRADE_CLOCK_MIDDAY_REVIEW_TIMEOUT_MINUTES = 10
TRADE_CLOCK_AFTERNOON_EXECUTION_TIMEOUT_MINUTES = 30
TRADE_CLOCK_AFTERNOON_SHADOW_TIMEOUT_MINUTES = 20
TRADE_CLOCK_SUMMARY_TIMEOUT_MINUTES = 20
TRADE_CLOCK_FALLBACK_MAX_PORTFOLIO_AGE_HOURS = 96
TRADE_CLOCK_FALLBACK_REQUIRE_RELEASE = False
TRADE_CLOCK_LIVE_SNAPSHOT_REFRESH_ENABLED = True
TRADE_CLOCK_LIVE_SNAPSHOT_REFRESH_FAIL_OPEN = True
TRADE_CLOCK_LIVE_SNAPSHOT_LOOP_ENABLED = True
TRADE_CLOCK_LIVE_SNAPSHOT_LOOP_INTERVAL_SECONDS = 3
TRADE_CLOCK_LIVE_SNAPSHOT_LOOP_MARKET_STAGES = ["morning_session", "afternoon_session", "closing_auction"]
TRADE_CLOCK_LIVE_SNAPSHOT_REFRESH_PHASES = [
    "preopen_gate",
    "simulation",
    "shadow",
    "midday_review",
    "afternoon_execution",
    "afternoon_shadow",
    "summary",
]
TRADE_CLOCK_SIMULATION_NAMESPACE = "precision"
TRADE_CLOCK_SHADOW_NAMESPACE = "shadow"
TRADE_CLOCK_SHADOW_ENABLED = False
TRADE_CLOCK_AFTERNOON_SHADOW_ENABLED = False
TRADE_CLOCK_SIMULATION_EXECUTION_MODE = "precision"
TRADE_CLOCK_SHADOW_EXECUTION_MODE = "precision"
TRADE_CLOCK_SIMULATION_PRECISION_TRADE = True
TRADE_CLOCK_SHADOW_PRECISION_TRADE = True
TRADE_CLOCK_SIMULATION_IGNORE_MARKET_PANIC_REDUCE_ONLY = True
TRADE_CLOCK_SHADOW_IGNORE_MARKET_PANIC_REDUCE_ONLY = True
TRADE_CLOCK_SIMULATION_ALLOW_UNFINISHED_ORDERS_RECONCILE = False
TRADE_CLOCK_SHADOW_ALLOW_UNFINISHED_ORDERS_RECONCILE = False
# T overlay: tighten proxy spread / per-symbol T ratio when portfolio concentration is elevated (see clock_account_snapshot)
T_OVERLAY_HIGH_RISK_MAX_PROXY_SPREAD = 0.015
T_OVERLAY_ELEVATED_MAX_PROXY_SPREAD = 0.018
T_OVERLAY_HIGH_RISK_MAX_RATIO_MULTIPLIER = 0.65
T_OVERLAY_ELEVATED_MAX_RATIO_MULTIPLIER = 0.82
ENABLE_AFFORDABLE_DATA_BUNDLE = True
AFFORDABLE_DATA_BUNDLE_RUN_BEFORE_RESEARCH = True
AFFORDABLE_DATA_BUNDLE_FAIL_OPEN = True
AFFORDABLE_DATA_BUNDLE_DAILY_LOOKBACK = 3
AFFORDABLE_DATA_BUNDLE_ANNOUNCEMENT_LOOKBACK = 30
AFFORDABLE_DATA_BUNDLE_TIMEOUT_MINUTES = 120
ENABLE_RESEARCH_FACT_REFRESH = True
RESEARCH_FACT_REFRESH_RUN_BEFORE_RESEARCH = True
RESEARCH_FACT_REFRESH_FAIL_OPEN = True
RESEARCH_FACT_EVENT_LOOKBACK_DAYS = 60
RESEARCH_FACT_HARD_FACTOR_LOOKBACK_DAYS = 5
RESEARCH_FACT_REFRESH_TIMEOUT_MINUTES = 90
ENABLE_DERIVED_ALPHA_REFRESH = True
DERIVED_ALPHA_REFRESH_RUN_BEFORE_RESEARCH = True
DERIVED_ALPHA_REFRESH_FAIL_OPEN = False
ENABLE_EXTERNAL_RESEARCH_REFRESH = True
EXTERNAL_RESEARCH_REFRESH_RUN_BEFORE_RESEARCH = True
EXTERNAL_RESEARCH_REFRESH_FAIL_OPEN = True
EXTERNAL_RESEARCH_FETCH_TIMEOUT_SECONDS = 20
EXTERNAL_RESEARCH_QIANZHAN_ENABLED = True
EXTERNAL_RESEARCH_QIANZHAN_DAILY_PAGE_BUDGET = 24
EXTERNAL_RESEARCH_GGZY_ENABLED = True
EXTERNAL_RESEARCH_GGZY_MAX_NOTICES_PER_RUN = 36
EXTERNAL_RESEARCH_LLM_ENRICHMENT_ENABLED = True
EXTERNAL_RESEARCH_LLM_PROVIDER = "deepseek_worker"
EXTERNAL_RESEARCH_LLM_TIMEOUT_SECONDS = 30
ENABLE_T_AUDIT = True
ENABLE_AUDIT_SITE_PUBLISH = True
AUDIT_SITE_PUBLISH_RUN_AFTER_SUMMARY = True
AUDIT_SITE_PUBLISH_FAIL_OPEN = True
AUDIT_SITE_PUBLISH_TIMEOUT_MINUTES = 20
ENABLE_INTRADAY_STATE_MACHINE = True
# 盘中战术层：在战略 release 之上产出增量意图，经 OMS 合并后下单（见 engine/intraday_tactics）
ENABLE_INTRADAY_TACTICS = True
INTRADAY_TACTICS_ARTIFACT_ROOT = str(Path(REPO_ROOT) / "data" / "trade_clock" / "intraday_tactics")
INTRADAY_TACTICAL_MAX_DAILY_TURNOVER_RATIO = 0.12
INTRADAY_TACTICAL_MAX_SYMBOL_ADD_RATIO = 0.06
INTRADAY_TACTICAL_MAX_SYMBOL_REDUCE_RATIO = 0.25
INTRADAY_TACTICAL_BUY_COOLDOWN_MINUTES = 18
INTRADAY_TACTICAL_SELL_COOLDOWN_MINUTES = 5
INTRADAY_TACTICAL_ALLOW_ADD_ON_SNAPSHOT_DEGRADED = True
INTRADAY_TACTICAL_ALLOW_REDUCE_ON_SNAPSHOT_DEGRADED = True
# True=日内 CSV 仍标成 shadow 整合；下午是否合并 overlay 由 INTRADAY_AFTERNOON_OVERLAY_RESPECT_SHADOW_MODE 单独控制（默认 False=下午仍应用 overlay）
INTRADAY_STATE_MACHINE_SHADOW_MODE = True
INTRADAY_AFTERNOON_OVERLAY_RESPECT_SHADOW_MODE = False
INTRADAY_STATE_MACHINE_FAIL_OPEN = True
INTRADAY_STATE_MACHINE_ENABLE_AFTERNOON_OVERLAY = True
INTRADAY_STATE_MACHINE_STALE_ORDER_MINUTES = 20
# True=若盘中状态机刷新 ran 且 ok=False，则跳过该相位子进程（preopen/simulation/shadow/midday/下午/战术相位）；默认 False 与历史 fail_open 一致
INTRADAY_STATE_MACHINE_STRICT_PRE_EXECUTION_GATE = False
ENABLE_EXECUTION_TIMING_LAYER = True
ENABLE_T_OVERLAY = True
TIMING_LAYER_BUY_SCORE_THRESHOLD = 0.58
TIMING_LAYER_SELL_SCORE_THRESHOLD = 0.62
TIMING_LAYER_REQUIRE_OMS_CLEAN_STATE = False
TIMING_LAYER_REQUIRE_FLOW_CONFIRMATION = False
TIMING_LAYER_ENABLE_AFTERNOON_SECOND_LEG = True
T_OVERLAY_MAX_ROUNDS_PER_SYMBOL_PER_DAY = 1
T_OVERLAY_MAX_RATIO_PER_SYMBOL = 0.20
T_OVERLAY_DISABLE_ON_PANIC = False
T_OVERLAY_DISABLE_ON_MAJOR_EVENT = True
TIMING_LAYER_WINDOW_CONFIG = {
    "open_noise_window": {
        "start": "09:30:00",
        "end": "09:40:00",
        "allow_trim": True,
        "allow_exit": True,
    },
    "morning_primary_window": {
        "start": "09:40:00",
        "end": "10:30:00",
        "allow_new_entry": True,
        "allow_build_entry": True,
        "allow_trim": True,
        "allow_exit": True,
        "allow_t_first_leg": True,
    },
    "mid_morning_low_speed_window": {
        "start": "10:30:00",
        "end": "11:20:00",
        "allow_trim": True,
        "allow_exit": True,
        "allow_reconcile": True,
    },
    "afternoon_primary_window": {
        "start": "13:00:00",
        "end": "14:20:00",
        "allow_new_entry": True,
        "allow_build_entry": True,
        "allow_trim": True,
        "allow_exit": True,
        "allow_t_second_leg": True,
    },
    "late_afternoon_reconcile_window": {
        "start": "14:20:00",
        "end": "14:50:00",
        "allow_trim": True,
        "allow_exit": True,
        "allow_reconcile": True,
        "allow_t_second_leg": True,
    },
    "post_1450_close_only_window": {
        "start": "14:50:00",
        "end": "15:00:00",
        "allow_exit": True,
        "allow_reconcile": True,
    },
}
INTRADAY_STATE_MACHINE_REFRESH_PHASES = [
    "preopen_gate",
    "simulation",
    "shadow",
    "midday_review",
    "afternoon_execution",
    "afternoon_shadow",
    "summary",
    "intraday_tactical_0940",
    "intraday_tactical_1010",
    "intraday_tactical_1040",
    "intraday_tactical_1310",
    "intraday_tactical_1350",
    "intraday_tactical_1420",
]
AFFORDABLE_DATA_BUNDLE_DATASETS = [
    "stock_basic",
    "daily",
    "adj_factor",
    "daily_basic",
    "forecast",
    "express",
    "dividend",
    "stk_holdertrade",
    "ggt_daily",
    "moneyflow_hsgt",
    "hk_hold",
    "margin",
    "margin_detail",
    "moneyflow",
    "stk_limit",
    "customs_summary",
]
ENABLE_SAFETY_LAYER = True
SAFETY_HEALTH_PROBE_INTERVAL_SECONDS = 300
SAFETY_ACCOUNT_STATE_MAX_AGE_SECONDS = 900
SAFETY_POSITION_SYNC_MAX_AGE_SECONDS = 900
SAFETY_RELEASE_MAX_AGE_SECONDS = 172800
SAFETY_FAIL_ON_UNFINISHED_ORDERS = True
SAFETY_FAIL_ON_UNKNOWN_ORDER_STATUS = True
SAFETY_DEGRADED_REDUCE_ONLY = True
SAFETY_CAUTION_TURNOVER_MULTIPLIER = 0.5
SAFETY_CAUTION_MARKET_MEAN_PCT_CHG = -1.0
SAFETY_PANIC_MARKET_MEAN_PCT_CHG = -2.2
SAFETY_CAUTION_HS300_RETURN_PCT = -1.5
SAFETY_PANIC_HS300_RETURN_PCT = -3.0
SAFETY_CAUTION_LIMIT_DOWN_RATIO = 0.05
SAFETY_PANIC_LIMIT_DOWN_RATIO = 0.12
SAFETY_EXECUTION_FAIL_RATIO_DEGRADED = 0.35
SAFETY_EXECUTION_FAIL_RATIO_HALT = 0.75
SAFETY_EXECUTION_FAIL_MIN_ORDERS = 3

HIGH_VALUE_TITLE_KEYWORDS = [
    "业绩预告", "业绩快报", "年度报告", "半年度报告", "一季度报告", "三季度报告",
    "回购", "分红", "权益分派", "增持", "减持", "定向增发", "发行股份", "可转债",
    "并购", "重组", "重大合同", "中标", "停牌", "复牌", "风险提示", "问询函", "处罚",
    "诉讼", "仲裁", "要约收购", "股份解除限售",
]

PACKAGE_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = PACKAGE_ROOT.parents[1]
DATA_ROOT = Path(os.environ.get("ASHARE_DATA_ROOT", str(REPO_ROOT / "data"))).resolve()

PORTFOLIO_OUTPUT_ROOT = str(DATA_ROOT / "portfolio_recommendation_v6")
TRAIN_TABLE_DIR = str(DATA_ROOT / "ml_datasets" / "train_table_v1")
HUB_OUTPUT_ROOT = str(DATA_ROOT / "ml_runs" / "research_engine")
RAW_EVENT_ROOT = str(DATA_ROOT / "event_lake_v6" / "raw")
EVENT_STORE_ROOT = str(DATA_ROOT / "event_lake_v6" / "curated")
INVENTORY_ROOT = str(DATA_ROOT / "event_lake_v6" / "inventory")
RESEARCH_ROOT = str(DATA_ROOT / "event_lake_v6" / "research")
BRIDGE_ROOT = str(DATA_ROOT / "event_lake_v6" / "bridge")
MARKET_STATE_ROOT = str(DATA_ROOT / "market_state_v6")
DAILY_CACHE_ROOT = str(DATA_ROOT / "daily_cache_v6")
LOG_ROOT = str(DATA_ROOT / "event_lake_v6" / "logs")
ENRICHED_DAILY_DIR = str(DATA_ROOT / "enriched_daily_csv_qfq")
TRADABILITY_FLAGS_PATH = str(DATA_ROOT / "auxiliary_data" / "tradability_flags.csv")
HS300_DAILY_PATH = str(DATA_ROOT / "index_daily_csv" / "000300_HS300.csv")
HS300_MEMBERSHIP_HISTORY_PATH = str(DATA_ROOT / "auxiliary_data" / "hs300_membership_history.csv")
LISTING_MASTER_PATH = str(DATA_ROOT / "auxiliary_data" / "listing_date_master.csv")
STOCK_UNIVERSE_CLEAN_PATH = str(DATA_ROOT / "auxiliary_data" / "stock_universe_clean.csv")
LIVE_EXECUTION_ROOT = str(DATA_ROOT / "live_execution_bridge")
LIVE_PRICE_SNAPSHOT_PATH = str(DATA_ROOT / "live_execution_bridge" / "daily_price_snapshot.csv")
TRADE_RELEASE_ROOT = str(DATA_ROOT / "trade_release_v1")
TRADE_CLOCK_ROOT = str(DATA_ROOT / "trade_clock")
INTRADAY_PROXY_ROOT = str(Path(TRADE_CLOCK_ROOT) / "intraday_proxy")
EXTERNAL_RESEARCH_ROOT = str(DATA_ROOT / "external_research_feeds" / "latest")
EXECUTION_LLM_REVIEW_ARTIFACT_ROOT = str(Path(TRADE_CLOCK_ROOT) / "llm_execution_review")
PORTFOLIO_CANDIDATE_LLM_ARTIFACT_ROOT = str(Path(TRADE_CLOCK_ROOT) / "candidate_pool_llm_review")
AUTOMATION_RUNS_ROOT = str(REPO_ROOT / "outputs" / "automation_runs")
TRADING_CALENDAR_CACHE_PATH = str(DATA_ROOT / "market_state_v6" / "trading_calendar_a_share.csv")
INDUSTRY_ROUTER_OUTPUT_ROOT = str(Path(RESEARCH_ROOT) / "industry_router")
INTEGRATED_THESIS_ROOT = str(Path(RESEARCH_ROOT) / "integrated_thesis")
TECHNICAL_CONFIRMATION_ROOT = str(Path(RESEARCH_ROOT) / "technical_confirmation")
OMS_OUTPUT_ROOT = str(Path(LIVE_EXECUTION_ROOT) / "oms_v1")
INTRADAY_STATE_MACHINE_ROOT = str(Path(TRADE_CLOCK_ROOT) / "intraday_state")
AFFORDABLE_SQLITE_PATH = str(DATA_ROOT / "sql_store" / "affordable_data_v1.sqlite3")
RESEARCH_FACT_SQLITE_PATH = str(DATA_ROOT / "sql_store" / "research_fact_layers_v1.sqlite3")
# 主研究库 runtime_json_artifacts / runtime_table_rows：release、OMS、盘中战术/状态机等镜像；读路径优先 SQL
ENABLE_RUNTIME_DATA_SQL_STORE = True
RUNTIME_DATA_SQLITE_PATH = str(DATA_ROOT / "sql_store" / "research_data_v1.sqlite3")
RUNTIME_DATA_SQL_PREFER_FOR_ROUTER = False
AFFORDABLE_SNAPSHOT_ROOT = str(DATA_ROOT / "affordable_feeds" / "latest")
MANUAL_EVENT_PROXY_PATH = str(Path(RESEARCH_ROOT) / "manual_event_proxy" / "manual_event_proxy.jsonl")
AFFORDABLE_DATA_BUNDLE_SCRIPT_PATH = str(REPO_ROOT / "scripts" / "update_affordable_data_bundle.py")
RESEARCH_FACT_EVENT_SCRIPT_PATH = str(REPO_ROOT / "scripts" / "build_event_fact_layer.py")
RESEARCH_FACT_HARD_FACTOR_SCRIPT_PATH = str(REPO_ROOT / "scripts" / "build_industry_hard_factor_layer.py")
EXTERNAL_RESEARCH_REFRESH_SCRIPT_PATH = str(REPO_ROOT / "scripts" / "update_external_research_feeds.py")
EXTERNAL_RESEARCH_SEED_PATH = str(REPO_ROOT / "configs" / "external_sources" / "qianzhan_seed_urls.json")
EXTERNAL_RESEARCH_QIANZHAN_COOKIE_HEADER_PATH = str(DATA_ROOT / "private" / "qianzhan_cookie_map.json")
AUDIT_SITE_PUBLISH_SCRIPT_PATH = str(REPO_ROOT / "scripts" / "publish_audit_report_to_site.ps1")
AUDIT_SITE_PUBLISH_POWERSHELL = "powershell.exe"
AUDIT_SITE_PUBLISH_REMOTE_USER = "ubuntu"
AUDIT_SITE_PUBLISH_REMOTE_HOST = "43.129.28.141"
AUDIT_SITE_PUBLISH_REMOTE_ROOT = "/var/www/peng1145141919810.xyz/site"
AUDIT_SITE_PUBLISH_DOMAIN = "peng1145141919810.xyz"
T_AUDIT_OUTPUT_ROOT = str(DATA_ROOT / "audit_v1")
T_AUDIT_POLICY_PATH = str(PACKAGE_ROOT / "configs" / "t_overlay" / "t_audit_policy.json")
TRAIN_APPEND_LOOKBACK_ROWS = 160
TRAIN_APPEND_PREFIX = "part_live_append"
SYNC_TUSHARE_MISSING_DAYS = True

# 主研究链 / canonical 子进程：使用仓库 .venv（Python 3.14 + requirements 全量），勿用裸的 Python314 安装目录（缺 pypdf 等）。
# 勿与掘金 Gmtrade 的 3.9 混用。
_DEFAULT_RESEARCH_PYTHON = REPO_ROOT / ".venv313" / "Scripts" / "python.exe"
if not _DEFAULT_RESEARCH_PYTHON.exists():
    _DEFAULT_RESEARCH_PYTHON = REPO_ROOT / ".venv" / "Scripts" / "python.exe"
PYTHON_EXECUTABLE = os.environ.get("ASHARE_RESEARCH_PYTHON", str(_DEFAULT_RESEARCH_PYTHON.resolve()))
V5_PROJECT_ROOT = str(PACKAGE_ROOT / "research_brain")
V5_HUB_OUTPUT_ROOT = str(DATA_ROOT / "research_hub_integrated")
V5_BRIDGE_INPUT_ROOT = BRIDGE_ROOT
# 掘金 Gmtrade 桥接专用解释器（与主栈隔离；若使用独立 venv，请改为该 venv 的 Scripts\python.exe）。
GMTRADE_PYTHON_EXECUTABLE = r"C:\Users\Administrator\AppData\Local\Programs\Python\Python39\python.exe"
GMTRADE_RUNTIME_CONFIG_TEMPLATE = str(PACKAGE_ROOT / "configs" / "gmtrade_runtime_config.example.json")
GMTRADE_RUNTIME_AUTOGEN_PATH = str(PACKAGE_ROOT / "configs" / "gmtrade_runtime_config.autogen.json")
GMTRADE_BRIDGE_SCRIPT_PATH = str(PACKAGE_ROOT / "run_gmtrade_portfolio_bridge.py")
GMTRADE_HEALTH_PROBE_SCRIPT_PATH = str(PACKAGE_ROOT / "run_gmtrade_health_probe.py")
INDUSTRY_ROUTER_CONTRACT_ROOT = str(PACKAGE_ROOT / "configs" / "industry_router")
MARKET_STATE_CONFIG_PATH = str(PACKAGE_ROOT / "configs" / "market_state" / "default.json")
TECHNICAL_CONFIRMATION_CONFIG_PATH = str(PACKAGE_ROOT / "configs" / "technical_confirmation" / "default.json")

OPENAI_MODEL = "gpt-5.4"
OPENAI_RESEARCH_FALLBACK_MODELS = ["gpt-4.1", "gpt-4o"]
DEEPSEEK_MODEL = "deepseek-chat"
DEEPSEEK_RESEARCH_FALLBACK_MODELS = ["deepseek-chat", "deepseek-reasoner"]
OPENAI_BASE_URL = "https://api.openai.com/v1"
DEEPSEEK_BASE_URL = "https://api.deepseek.com"
TUSHARE_TOKEN_ENV = "TUSHARE_TOKEN"
TUSHARE_TOKEN = ""
OPENAI_API_KEY_ENV = "OPENAI_API_KEY"
DEEPSEEK_API_KEY_ENV = "DEEPSEEK_API_KEY"

OLLAMA_BASE_URL = "http://localhost:11434"
OLLAMA_MODEL = "qwen2.5:7b"  # legacy shared default
OLLAMA_TIMEOUT_SECONDS = 120  # legacy shared default
OLLAMA_EVENT_EXTRACT_MODEL = "qwen2.5:7b"
OLLAMA_EVENT_EXTRACT_TIMEOUT_SECONDS = 120
OLLAMA_RESEARCH_MODEL = "deepseek-r1:14b"
OLLAMA_RESEARCH_FALLBACK_MODELS = ["deepseek-r1:14b", "qwen2.5:7b"]
OLLAMA_RESEARCH_TIMEOUT_SECONDS = 180
ENABLE_LOCAL_OLLAMA_EVIDENCE_CARD = True
OLLAMA_EVIDENCE_CARD_MODEL = "deepseek-r1:14b"
OLLAMA_EVIDENCE_CARD_TIMEOUT_SECONDS = 180
OLLAMA_EVIDENCE_CARD_MAX_ITEMS = 2
ENABLE_LOCAL_OLLAMA_REVIEW_ROUTER = True
OLLAMA_REVIEW_ROUTER_MODEL = "qwen2.5:7b"
OLLAMA_REVIEW_ROUTER_TIMEOUT_SECONDS = 90
OLLAMA_REVIEW_ROUTER_MAX_ITEMS = 6
ENABLE_LOCAL_OLLAMA_RUNTIME_EXPLAINER = True
OLLAMA_RUNTIME_EXPLAINER_MODEL = "qwen2.5:7b"
OLLAMA_RUNTIME_EXPLAINER_TIMEOUT_SECONDS = 45
OLLAMA_RUNTIME_EXPLAINER_STAGES = ["v6_planning", "v5_gpu", "portfolio_recommendation", "execution_bridge"]
ENABLE_LOCAL_OLLAMA_V5_REVIEW = True
OLLAMA_V5_REVIEW_MODEL = "deepseek-r1:14b"
OLLAMA_V5_REVIEW_TIMEOUT_SECONDS = 180
LLM_TRACE_ARTIFACT_ROOT = str(Path(TRADE_CLOCK_ROOT) / "llm_trace")
LLM_TRACE_PROMPT_CHAR_CAP = 4000
LLM_TRACE_RAW_RESPONSE_CHAR_CAP = 4000
LLM_TRACE_STORE_PROMPTS = True
LLM_TRACE_STORE_RAW_RESPONSE = True
